name: "Releaser"
description: "Releaser creates tag if changes are found since the latest release to main branch."
inputs:
  token:
    description: "Personal access token with repo permission"
    required: true
    default: ""
  gate:
    description: "Name of the dev workflow acting as gate - workflow needs to pass for release to happen. Separate multiple workflows with comma."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: dev
        token: ${{ inputs.token }}
    - run: |
        git config --global user.name release-bot
        git config --global user.email release-bot
      shell: bash
    - run: ${{ github.action_path }}/release.sh
      shell: bash
      env:
        GATE: ${{ inputs.gate }}
        WORKFLOW_BADGE: https://github.com/${{ github.repository }}/actions/workflows/WORKFLOW_NAME.yml/badge.svg?branch=dev
