name: "Releaser"
description: "Releaser creates tag if changes are found since the latest release to main branch."
inputs:
  token:
    description: "Personal access token with repo permission"
    required: true
    default: ""
  gate:
    description: "Name of the dev workflow acting as gate - workflow needs to pass for release to happen."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: dev
        token: ${{ inputs.token }}
    - run: |
        git config --global user.name release-bot
        git config --global user.email release-bot
      shell: bash
    - run: ${{ github.action_path }}/release.sh
      shell: bash
      env:
        BADGE: https://github.com/$GITHUB_REPOSITORY/actions/workflows/${{ inputs.gate }}.yml/badge.svg?branch=dev
