name: release
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - run: |
          git config --global user.name release-bot
          git config --global user.email release-bot
      - name: push
        run: |
          git fetch --tags origin
          latest=$(git describe --tags --abbrev=0 || echo "v0")
          new_version=v$((${latest//v}+1))
          echo "Releasing new version $new_version"
          git tag -a -m "Release $new_version" $new_version
          git push origin $new_version
