name: release
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: merge
        run: |
          git fetch --tags origin
          latest=$(git describe --tags --abbrev=0 || echo "v0")
          new_version=v$((${latest//v}+1))
          git tag -a -m "Release $new_version" $new_version
          git push --follow-tags
